---
- hosts: localhost
  any_errors_fatal: false
  ignore_errors: yes
  tasks:
    - name: install git
      become: 'yes'
      package:
        name: git
        state: present

    - name: checkout konstruktoid.hardening
      become: 'yes'
      ansible.builtin.git:
        repo: 'https://github.com/konstruktoid/ansible-role-hardening'
        dest: /etc/ansible/roles/konstruktoid.hardening
        version: master

    - name: include the hardening role
      include_role:
        name: konstruktoid.hardening
      vars:
        block_blacklisted: true
        suid_sgid_permissions: false
...
