name: Docker Base Auto Update CI

on:
  schedule:
    - cron: "23 13 3 * *"

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/rockylinux:8
          image: simeononsecurity/docker-rocky-hardened:latest
      - name: Checkout
        uses: actions/checkout@v3
        if: steps.check.outputs.needs-updating == 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.check.outputs.needs-updating == 'true'
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
        if: steps.check.outputs.needs-updating == 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.check.outputs.needs-updating == 'true'
      - name: Build the Docker image
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/arm64 -t simeononsecurity/docker-rocky-hardened:latest --progress=plain --push .
        if: steps.check.outputs.needs-updating == 'true'
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: simeononsecurity/docker-rocky-hardened:latest
        if: steps.check.outputs.needs-updating == 'true'
